# --------------------------------------------------
# 🧑‍💻 Etapa de Desenvolvimento do Vite
# --------------------------------------------------
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache python3 make g++

# Copia apenas arquivos de dependências
COPY package*.json ./
RUN npm install

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

# Montaremos o código como volume (não copiamos tudo)
# Isso evita rebuilds ao editar o código local

EXPOSE 5173

# Permite hot reload dentro do container (para Windows/Mac)
ENV CHOKIDAR_USEPOLLING=true
ENV HOST=0.0.0.0

CMD ["npm", "run", "dev"]
