services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    command: >
      gunicorn auto_data_analysis.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      --timeout 1000
      --log-level info
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # 👇 Passa a URL pública da API para o build do Vite
        VITE_API_URL: "https://xclarity.duckdns.org/api"
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
