services:
  # =============================
  # 🔹 BACKEND DJANGO + GUNICORN
  # =============================
  backend:
    image: 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-backend:latest
    container_name: backend
    env_file:
      - ./backend/.env
    expose:
      - "8000"
    restart: always
    depends_on:
      - redis
    networks:
      - app-network


  # =============================
  # 🔹 FRONTEND (React + Nginx)
  # =============================
  frontend:
    image: 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-frontend:latest
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "8080:80"
    restart: always
    networks:
      - app-network

  # =============================
  # 🔹 REDIS (broker Celery)
  # =============================
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  # =============================
  # 🔹 CELERY WORKER
  # =============================
  worker:
    image: 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-backend:latest
    container_name: celery-worker
    command: celery -A auto_data_analysis worker --loglevel=INFO
    env_file:
      - ./backend/.env
    depends_on:
      - backend
      - redis
    restart: always
    networks:
      - app-network

  # =============================
  # (Opcional) CELERY BEAT - agendador
  # =============================
  # beat:
  #   image: 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-backend:latest
  #   container_name: celery-beat
  #   command: celery -A auto_data_analysis beat --loglevel=INFO
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     - redis
  #   restart: always
  #   networks:
  #     - app-network

# =============================
# 🔹 REDE COMPARTILHADA (mantida)
# =============================
networks:
  app-network:
    driver: bridge
