name: Pipeline CI/CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  job1:
    name: build_ecr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.3.1
        with:
          role-to-assume: arn:aws:iam::165814550670:role/GitHubActionsApp
          aws-region: us-east-1

      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2.0.1
      
      - name: Build, Tag, and Push image to Amazon ECR
        run: |
            docker build -t xclarity-frontend:latest ./frontend
            docker build -t xclarity-backend:latest ./backend

            docker tag xclarity-frontend:latest 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-frontend:latest
            docker tag xclarity-backend:latest 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-backend:latest

            # Push para o ECR
            docker push 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-frontend:latest
            docker push 165814550670.dkr.ecr.us-east-1.amazonaws.com/xclarity-backend:latest

  job2:
    name: deploy_ec2
    needs: job1
    env: 
        INSTANCE_KEY: ${{secrets.INSTANCE_KEY}} 
        PUBLIC_IP: ${{secrets.PUBLIC_IP}}
    runs-on: ubuntu-latest

    steps:

        - name: Deploy EC2 via SSH
          run: |
            echo "$INSTANCE_KEY" > chave-site.pem
            chmod 400 chave-site.pem

            ssh -i chave-site.pem -o StrictHostKeyChecking=no ubuntu@$PUBLIC_IP << 'EOF'

                echo "🧹 Limpando tudo por falta de espaço..."
                docker stop $(docker ps -aq) 2>/dev/null || true
                docker rm $(docker ps -aq) 2>/dev/null || true

                docker system prune -af --volumes

                echo "🔐 Login no ECR..."
                aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 165814550670.dkr.ecr.us-east-1.amazonaws.com

                echo "⬇ Puxando apenas imagens latest..."
                docker compose -f docker-compose.yml pull

                echo "🚀 Subindo stack mantendo a network interna..."
                docker compose -f docker-compose.yml up -d --remove-orphans

                echo "✅ Deploy concluído!"
                docker ps
            EOF

            rm chave-site.pem
